### PR TITLE
3rd commit

### PR DESCRIPTION
**Pull request by rewerb4**
js and ajax

### CODE REVIEW

**Comment by kathytrinh81** [comment]
Everything should be completed. Let me know you input.
Thanks.

```
 On Thursday, April 2, 2015 11:03 PM, rewerb4 <notifications@github.com> wrote:
```

 Merged #2.—

**Comment by rewerb4** [comment]
I am not seeing any of your changes? We will go over it tonight in class

**Comment by kathytrinh81** [comment]
i didn't put them up to the GitHub yet because I wasn't sure how to merge it correctly. I only sent you the files as attachment.

```
 On Monday, April 6, 2015 10:17 AM, rewerb4 <notifications@github.com> wrote:
```

 I am not seeing any of your changes? We will go over it tonight in class—

**Comment by rewerb4** [comment]
I'm not seeing any attachments. Try sending it to my weber mail.
mathewbrewer@mail.weber.edu

**Pull request merged**
